name: paxapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.0-146.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  mobile_scanner: ^3.0.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/